### ISSUE TITLE
Add mechanism to start a nix-shell with a selected environment

### ISSUE THREAD

**Issue by Mic92** [nix-community/nix-environments#1]
I thought about:

```nix
# default.nix
{
  openwrt = import ./envs/openwrt/shell.nix;
}
```

```console
$ nix-shell https://github.com/nix-community/nix-environments/archive/master.tar.gz -A openwrt
```

any better ideas? @zimbatm @Infinisil

**Comment by Infinisil** [comment]
I don't think there's any alternative to this suggestion :)

**Comment by Mic92** [comment]
Another way could be:

```nix
let
  env = import(fetchurl {
    url = "https://github.com/nix-community/nix-environments/archive/master.tar.gz";
    sha256 = "";
  }).openwrt { inherit pkgs; };
in (env.overrideAttrs (old: {
  buildInputs = old.buildInputs ++ [];
}))
```

**Comment by Mic92** [comment]
fixed in https://github.com/nix-community/nix-environments/commit/bc330e68209ed058613dac9460dba11a5486e335

Too bad that one cannot override buildFHSEnv in a meaningful way.

**Comment by zimbatm** [comment]
@Mic92 is the idea to provide a set of "common" development profiles? Like a ruby / go / nodejs / ... dev environments?

**Comment by Mic92** [comment]
@zimbatm isn't that already the goal of nixpkgs itself or its *2nix helper? I was more thinking of having specific nix-shells that one can use when working on a project: https://github.com/nix-community/nix-environments/tree/master/envs
In the past I was trying to push those upstream i.e. OpenWRT, but was they rejected those changes at the time. Instead I hope that we can share those expressions in a common repository so they stay up-to-date.

**Comment by zimbatm** [comment]
oh I misunderstood. You want out-of-tree shell.nix files. 

Did you see https://discourse.nixos.org/t/better-package-development-with-nix-pin-and-nix-update-source/257 already?

**Comment by zimbatm** [comment]
I am pretty sure somebody was already working on this but I can't find it anymore. Maybe it was @layus

**Comment by Mic92** [comment]
I probably should re-word the description of the project.

**Comment by zimbatm** [comment]
It might be useful to have a frontend CLI to load the shell, this would allow to add some heuristics like check the git remotes and select the right shell based on that.

`nix-shell-remote [-p <project-name>] [--update] [<create|edit|enter>]`

**Comment by Mic92** [comment]
I also toughed about that. But let's first see how many contributions we get.

**Comment by layus** [comment]
> I am pretty sure somebody was already working on this but I can't find it anymore. Maybe it was @layus

Well, my idea was to make `nix-env -A openwrt` so efficient that a separate environment would not be useful.

Now, the main advantage I see in this project is that
1. Such environments would include autotools (which is not needed when building from released sources, but needed when building from git, as is the case with i3 and certainly many more).
2. Such environments could cover many separate packages, like python or ruby envs, but also complex packages split into parts. Or the full union of environments required to build a package and its dependencies.

I like the idea, but I have no clue where to start.

**Comment by ivanbrennan** [comment]
> It might be useful to have a frontend CLI to load the shell, this would allow to add some heuristics like check the git remotes and select the right shell based on that.
> 
> `nix-shell-remote [-p <project-name>] [--update] [create|edit|enter]`

I ended up implementing a CLI very much like this. It infers the project name from the basename of the git-remote, and uses a couple heuristics to infer the project version. It doesn't have any update/create functionality.

I wonder if it could be made useful to this project?
https://github.com/ivanbrennan/shellbit

**Comment by Mic92** [comment]
Yes indeed.
