### ISSUE TITLE
Slightly confusing docs for xilinx-vitis

### ISSUE THREAD

**Issue by dramforever** [nix-community/nix-environments#21]
Seems to have confused someone here https://discourse.nixos.org/t/fhs-env-for-installing-xilinx/13150/15

Subdirectory `README.md` says to `nix run`, but file is called `shell.nix`: https://github.com/nix-community/nix-environments/tree/630b107539e19fa1071f6cf966a0198176b2185a/envs/xilinx-vitis

Repo-level `README.md` just says `nix-shell` or `nix develop`: https://github.com/nix-community/nix-environments/tree/630b107539e19fa1071f6cf966a0198176b2185a#stable-nix

Only `nix run` seems to work. Which should be the right way then?

**Comment by Mic92** [comment]
Better? https://github.com/nix-community/nix-environments/pull/22
