### ISSUE TITLE
yocto environment fails with "BrokenPipeError: [Errno 32] Broken pipe"

### ISSUE THREAD

**Issue by jetm** [nix-community/nix-environments#55]
yocto environment builds fine just with poky, but in an environment using `nix-shell` with more layers and a HW with 32 threads, it starts failing with this error:

```
    >        worker.stdin.write(msg)

BrokenPipeError: [Errno 32] Broken pipe
```

In a Docker/Podman container works fine in the same setup.

**Comment by Mic92** [comment]
Sorry. I am not actually using yocto. This error can have many root causes.
Maybe try `strace`. I assume the process that the build script tries to write to dies for some reason.

If you can install `sysdig`.
You can use this:

```
sysdig -c stderr
```

Hope that helps.
