### ISSUE TITLE
Home assistant from git does not start properly

### ISSUE THREAD

**Issue by Ramblurr** [nix-community/nix-environments#59]
When starting home assistant from git (for local dev) a few components fail to start, failing with the error:

`ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory`

Full error:

![image](https://github.com/nix-community/nix-environments/assets/14830/4d5e4cbb-bf06-44bd-822b-7ce9e43d7ed7)

**Comment by Mic92** [comment]
Potential fix:

```
LD_LIBRARY_PATH = pkgs.stdenv.cc.cc;
```
